### ISSUE TITLE
php 8.1 not working conection error 

### ISSUE THREAD

**Issue by korb3n70** [krakorj/phpmodbus#11]
there are connection issues on php version 8.1 , (also php_socket enabled ) anyone has the same issue ? 
after the update from php 7.2 to 8.1  my process stop working , the only way  to get working is to switch to the previous version (7.2)  .

**Comment by ve2k** [comment]
@korb3n70: I got it working on php 8.1 with following two changes:
1. Apply IecType static function declaration fix: https://github.com/krakorj/phpmodbus/pull/10/commits/9293309c713ebf6ff849278251691bcc8fefa081
2. Change line 57 in ModbusMaster.php from
`  function ModbusMaster($host, $protocol){`
to
`  function __construct($host, $protocol){`

**Comment by krakorj** [comment]
Fixed, can you please test it? Thank you in advance

**Comment by korb3n70** [comment]
hello , just reverted to the php8.1 but i got a different error . 
below the error . 
PHP Fatal error:  Uncaught Error: Non-static method IecType::iecBYTE() cannot be called statically in /var                                                                                   /www/myhouse/script_task/Phpmodbus/ModbusMaster.php:477
Stack trace:
#0 /var/www/myhouse/script_task/Phpmodbus/ModbusMaster.php(432): ModbusMaster->readMultipleRegistersPacket                                                                                   Builder()
#1 /var/www/myhouse/script_task/cons.php(57): ModbusMaster->readMultipleRegisters()
#2 {main}
  thrown in /var/www/myhouse/script_task/Phpmodbus/ModbusMaster.php on line 477

Fatal error: Uncaught Error: Non-static method IecType::iecBYTE() cannot be called statically in /var/www/                                                                                   myhouse/script_task/Phpmodbus/ModbusMaster.php:477
Stack trace:
#0 /var/www/myhouse/script_task/Phpmodbus/ModbusMaster.php(432): ModbusMaster->readMultipleRegistersPacket                                                                                   Builder()
#1 /var/www/myhouse/script_task/cons.php(57): ModbusMaster->readMultipleRegisters()
#2 {main}
  thrown in /var/www/myhouse/script_task/Phpmodbus/ModbusMaster.php on line 477

**Comment by krakorj** [comment]
Ups, fixed, can you please test it again? Thank you in advance

**Comment by korb3n70** [comment]
hi, i'm very glad to say  "now it's  working!!"  ,, thank you :)
 switching the application to php 8.1 i will take an eye on this

**Comment by krakorj** [comment]
Great, beer for you for testing ;)
