### ISSUE TITLE
Deprecated using php7.3

### ISSUE THREAD

**Issue by tpvlinux** [krakorj/phpmodbus#6]
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; ModbusMaster has a deprecated constructor in /var/www/html/phpmodbus/Phpmodbus/ModbusMaster.php on line 38

Deprecated: Non-static method IecType::iecBYTE() should not be called statically in /var/www/html/phpmodbus/Phpmodbus/ModbusMaster.php on line 477

Deprecated: Non-static method IecType::iecINT() should not be called statically in /var/www/html/phpmodbus/Phpmodbus/ModbusMaster.php on line 479

Deprecated: Non-static method IecType::iecBYTE() should not be called statically in /var/www/html/phpmodbus/Phpmodbus/IecType.php on line 51

Deprecated: Non-static method IecType::iecBYTE() should not be called statically in /var/www/html/phpmodbus/Phpmodbus/IecType.php on line 52

Deprecated: Non-static method IecType::iecINT() should not be called statically in /var/www/html/phpmodbus/Phpmodbus/ModbusMaster.php on line 480

Deprecated: Non-static method IecType::iecBYTE() should not be called statically in /var/www/html/phpmodbus/Phpmodbus/IecType.php on line 51

Deprecated: Non-static method IecType::iecBYTE() should not be called statically in /var/www/html/phpmodbus/Phpmodbus/IecType.php on line 52

Deprecated: Non-static method IecType::iecINT() should not be called statically in /var/www/html/phpmodbus/Phpmodbus/ModbusMaster.php on line 484

Deprecated: Non-static method IecType::iecBYTE() should not be called statically in /var/www/html/phpmodbus/Phpmodbus/IecType.php on line 51

Deprecated: Non-static method IecType::iecBYTE() should not be called statically in /var/www/html/phpmodbus/Phpmodbus/IecType.php on line 52

Deprecated: Non-static method IecType::iecINT() should not be called statically in /var/www/html/phpmodbus/Phpmodbus/ModbusMaster.php on line 485

Deprecated: Non-static method IecType::iecBYTE() should not be called statically in /var/www/html/phpmodbus/Phpmodbus/IecType.php on line 51

Deprecated: Non-static method IecType::iecBYTE() should not be called statically in /var/www/html/phpmodbus/Phpmodbus/IecType.php on line 52

Deprecated: Non-static method IecType::iecINT() should not be called statically in /var/www/html/phpmodbus/Phpmodbus/ModbusMaster.php on line 486

Deprecated: Non-static method IecType::iecBYTE() should not be called statically in /var/www/html/phpmodbus/Phpmodbus/IecType.php on line 51

Deprecated: Non-static method IecType::iecBYTE() should not be called statically in /var/www/html/phpmodbus/Phpmodbus/IecType.php on line 52

Deprecated: Non-static method IecType::iecBYTE() should not be called statically in /var/www/html/phpmodbus/Phpmodbus/ModbusMaster.php on line 487

**Comment by krakorj** [comment]
Solved in scope of #11
