### ISSUE TITLE
combineBytes bug?

### ISSUE THREAD

**Issue by zmip** [krakorj/phpmodbus#7]
Hard to believe, because I'm seeing this in all the different forks of this project, but I think in combineBytes the byte order is wrong when $endianness is falsy:

```
if ($endianness == 0)
            $value = (($data[3] & 0xFF)<<16) |
                    (($data[2] & 0xFF)<<24) |
                    (($data[1] & 0xFF)) |
                    (($data[0] & 0xFF)<<8);
```

Errrr... no? That makes no sense. Shouldn't it just be a mirrored version of big endian:

```
if ($endianness == 0) {
	$value = (($data[3] & 0xFF)) |
		(($data[2] & 0xFF) << 8 ) |
		(($data[1] & 0xFF) << 16 ) |
		(($data[0] & 0xFF) << 24 );
```

What am I missing? Is no one ever using integers?

**Comment by zmip** [comment]
Alright, so it's not a bug per se, just a possibly wrong assumption. The modbus standard apparantly does not specify byte order, so depending on the implementation, this could either be "just fine" or "totally wrong". More info:

https://www.ni.com/nl-nl/innovations/white-papers/14/the-modbus-protocol-in-depth.html

Check out section "Data Endianness"

**Comment by krakorj** [comment]
@zmip the library has been tested to WAGO PLCs 750-841 series. The testing covered all data types like INT, UINT, WORD, DWORD etc. available via the controller modbus interface. Note the "endianning" is not just a switching of byte order. As you can see in https://en.wikipedia.org/wiki/Endianness#Files_and_filesystems section "Byte addressing":

> ... Middle-endian machines like the Honeywell 316 above complicate this even further: the 32-bit value is stored as two 16-bit words 'hn' 'Jo' in little-endian, themselves with a big-endian notation (thus 'h' 'n' 'J' 'o').

Nevertheless thank you for your suggestion, a switch to handle this "feature" would be nice.

**Comment by zmip** [comment]
> @krakorj Note the "endianning" is not just a switching of byte order. 

You are right, I jumpted the gun on this one. Coming from a C/C++ background, "endianning" normally is just that: switching the byte-order. But I now see that this is a legacy thing from the modbus spec (1970's, wow!), and it's not really endianness, but rather word-order and endianness. Indeed, it would be nice to be able to switch to all possible options.
